language: node_js
node_js:
  - "12"
before_script:
  - npm install
script: 
 - npm run build
- cp dist/conference-ionic/index.html dist/conference-ionic/404.html
deploy:
  local-dir: dist/conference-ionic
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  on:
    branch: master
notifications:
  email: false