language: node_js
node_js:
  - "12"
before_script:
 - npm i
 - npm i ionic cordova
script: 
 - npm run build
 - cp www/index.html www/404.html
deploy:
  local-dir: www
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  on:
    branch: master
notifications:
  email: false